### PR TITLE
fix runner to work with newer (Chrome-based) Opera browsers

### PR DESCRIPTION
**Pull request by zohararad**
I haven't tested this on Windows / Linux. Only on Mac, but it's basically a trimmed down copy of the Karma Chrome runner

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Sorry for the late feedback, but does that mean you can't use it with the old versions anymore?

**Comment by zohararad** [comment]
@Dignifiedquire indeed - the main issue here is the flags that are passed to the browser on startup, which changed once Opera moved to Chrome-based engine.

Perhaps this could be refactored into two distinct runners?

**Comment by Dignifiedquire** [comment]
Yes, we could do something like `karma-chrome-launcher` does and provide multiple launchers, one called `Opera` which works with the newer versions, and one called `OperaLegacy` which supports the current version. Are you up for changing your pr to do that? (I moved some code around just know so please be sure to rebase onto the latest master)

**Comment by zohararad** [comment]
Sure, let me see if I can get to it over the next couple of days

**Comment by Dignifiedquire** [comment]
Cool thanks

**Comment by zohararad** [comment]
@Dignifiedquire it's been quite a while since this PR was sent, so rebasing / merging results in quite a few conflicts, im not comfortable resolving.

Would you prefer that I resend a new PR off a fresh clone of this repo, or would you like to add the code yourself?

**Comment by Dignifiedquire** [comment]
If you could do a fresh PR that would be great, I probably don't have time to do it myself at the moment

**Pull request closed without merging**
