### PR TITLE
Support for Opera and Opera Classic launchers

### PR DESCRIPTION
**Pull request by zohararad**
This PR adds support for launching Opera Classic (v12) or Opera current (v15+)

@Dignifiedquire this replaces PR #8

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Thanks, could please make sure eslint passes and use single `var` assignments.

**Comment by zohararad** [comment]
Done

**Comment by Dignifiedquire** [comment]
Sorry for the late feedback, could you please rebase onto the latest master and squash the commits into one, with a commit message following our [convention](http://karma-runner.github.io/0.13/dev/git-commit-msg.html). Thanks.

**Comment by zohararad** [comment]
@Dignifiedquire done - Please let me know if ok.

**Comment by Dignifiedquire** [comment]
Thanks :octocat:

**Pull request merged**
